import {
  mdiSolarPowerVariantOutline,
  mdiArrowLeft,
  mdiMonitorDashboard,
  mdiAccountGroupOutline,
  mdiHumanGreetingProximity,
  mdiAccountPlusOutline,
  mdiAccountEditOutline,
  mdiCurrencyUsd,
  mdiCurrencyUsdOff,
  mdiMapMarkerPath,
  mdiTextBoxEditOutline,
  mdiRefresh,
  mdiClose,
  mdiCogOutline,
  mdiWalletBifold,
  mdiCashMultiple,
  mdiAlertCircleOutline,
  // mdiDownload,
  mdiInformationVariant,
  mdiCashLockOpen,
  mdiAlertOutline,
  mdiPower,
  mdiShieldLockOpenOutline,
  mdiCrowd,
  mdiChevronDoubleLeft,
  mdiSunClockOutline,
} from '@mdi/js';

export default {
  mdiSolarPowerVariantOutline,
  mdiArrowLeft,
  mdiMonitorDashboard,
  mdiAccountGroupOutline,
  mdiHumanGreetingProximity,
  mdiAccountPlusOutline,
  mdiAccountEditOutline,
  mdiCurrencyUsd,
  mdiCurrencyUsdOff,
  mdiMapMarkerPath,
  mdiTextBoxEditOutline,
  mdiRefresh,
  mdiClose,
  mdiCogOutline,
  mdiWalletBifold,
  mdiCashMultiple,
  mdiAlertCircleOutline,
  // mdiDownload,
  mdiInformationVariant,
  mdiCashLockOpen,
  mdiAlertOutline,
  mdiPower,
  mdiShieldLockOpenOutline,
  mdiCrowd,
  mdiChevronDoubleLeft,
  mdiSunClockOutline,
};
